name: Archive Build Logs

on:
  workflow_dispatch: # This triggers the workflow manually

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew build jacocoTestReport > ubuntu/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true
      - name: Archive build logs for Ubuntu
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-build-logs
          path: ubuntu/build-logs.txt # Archive the text file containing build logs
  
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew clean build > macos/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true
      - name: Archive build logs for macOS
        uses: actions/upload-artifact@v2
        with:
          name: macos-build-logs
          path: macos/build-logs.txt # Archive the text file containing build logs
  
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew clean build > windows/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true
      - name: Archive build logs for Windows
        uses: actions/upload-artifact@v2
        with:
          name: windows-build-logs
          path: windows/build-logs.txt # Archive the text file containing build logs
