name: Build pull request

on: pull_request

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Ubuntu Directory
        run: mkdir -p ubuntu
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and Save Logs for Ubuntu
        run: |
          ./gradlew build jacocoTestReport > ubuntu/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v1

  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create MacOS Directory
        run: mkdir -p macos
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and Save Logs for MacOS
        run: |
          ./gradlew clean build > macos/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Windows Directory
        run: mkdir -p windows
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and Save Logs for Windows
        run: |
          ./gradlew clean build > windows/build-logs.txt 2>&1
        env:
          TEST_MODE_ACTIVE: true
